# fly.toml app configuration file generated for pocketpages on 2024-08-30T11:11:13-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pocketpages'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "pb_data"
  destination = "/pb_data"
  initial_size = "20gb" # optional - the size of the volume created on first deploy